{% set version = "3.2.2" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: d068ca1dfd735fb92a07d33cb8f288adc0f6bc1287a139ca2425366f7cbe38f8

build:
  number: 0
  skip: True #[py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-config = pylint:_run_pylint_config
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - dill >=0.2    # [py<311]
    - dill >=0.3.6  # [py==311]
    - dill >=0.3.7  # [py>=312]
    - platformdirs >=2.2.0
    - astroid >=3.2.2,<3.3.0
    - isort >=4.2.5,<6,!=5.13.0
    - mccabe >=0.6,<0.8
    - tomli >=1.1.0  # [py<311]
    - tomlkit >=0.10.1
    - colorama >=0.4.5  # [win]
    - typing-extensions >=3.10.0  # [py<310]
  run_constrained:
    - gitpython >3
    - pyenchant >=3.2,<4

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
    - pylint.utils
  requires:
    - pip
  commands:
    - pip check
    - pylint --help
    - pylint-config --help
    - pyreverse --help
    - symilar --help

about:
  home: https://www.pylint.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  dev_url: https://github.com/PyCQA/pylint/

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
