{% set version = "2.12.1" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: 4f4a52b132c05b49094b28e109febcec6bfb7bc6961c7485a5ad0a0f961df289

build:
  number: 1
  # 6/11/2021: skip py<36 causes an unsatisfiable error on win32 with py36
  #skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  build:
    - python                   # [build_platform != target_platform]
  host:
    - python
    - pip
    - pytest-runner
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - astroid >=2.6.5,<=2.7
    - colorama  # [win]
    - isort >=4.2.5,<6
    - mccabe >=0.6,<0.7
    - python
    - toml >=0.7.1

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
    - pylint.utils
  requires:
    - pip
  commands:
    - pip check
    - pylint --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type epylint  # [unix]
    - where epylint  # [win]
    - pyreverse --help
    - symilar --help

about:
  home: https://www.pylint.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  doc_source_url: https://github.com/PyCQA/pylint/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/pylint/

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
