{% set version = "2.13.1" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: 7d5ea593303cf5ca567c60a8d475056825c7373f493ddb16308f09f5fe47f8f4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6.2
    - astroid >=2.9.0,<2.10
    - colorama  # [win]
    - isort >=4.2.5,<6
    - mccabe >=0.6,<0.8
    - platformdirs >=2.2.0
    - toml >=0.9.2
    - typing_extensions >=3.10

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
    - pylint.utils
  requires:
    - pip
  commands:
    # 2022/03/22: Disable pip check because
    # pylint 2.12.2 has requirement mccabe<0.7,>=0.6, but you have mccabe 0.7.0.
    # We can safely use mccabe 0.7.0 https://github.com/PyCQA/mccabe/compare/0.6.1...0.7.0, it was released after pylint 2.12.2 and it haven't broken changes
    #- pip check
    - pylint --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type epylint  # [unix]
    - where epylint  # [win]
    - pyreverse --help
    - symilar --help

about:
  home: https://www.pylint.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  doc_source_url: https://github.com/PyCQA/pylint/blob/master/doc/index.rst
  dev_url: https://github.com/PyCQA/pylint/

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
