{% set name = "pylint" %}
{% set version = "4.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a427fe76e0e5355e9fb9b604fd106c419cafb395886ba7f3cebebb03f30e081d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-config = pylint:_run_pylint_config
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=77
  run:
    - python
    - astroid >=4.0.2,<=4.1
    - colorama >=0.4.5  # [win]
    - dill >=0.2    # [py<311]
    - dill >=0.3.6  # [py==311]
    - dill >=0.3.7  # [py>=312]
    - isort >=5,!=5.13,<8
    - mccabe >=0.6,<0.8
    - platformdirs >=2.2
    - tomli >=1.1  # [py<311]
    - tomlkit >=0.10.1
  run_constrained:
    # testutils
    - gitpython >3
    # spelling
    - pyenchant >=3.2,<4

# >   assert self._clean_paths(expected_output.strip()) == actual_output.strip()
# E   AssertionError: assert 'Using config...g.py (2 of 2)' == 'Using config...g.py (2 of 2)'
{% set tests_to_skip = "test_progress_reporting" %}
# Hardcoded test output does not work in our test environment due to pylint being seen as a local package. Updating
# the function output was tested; however, dependant tests continue to fail. Disabling for now.
# https://github.com/pylint-dev/pylint/blob/v4.0.3/tests/functional/w/wrong_import_order.txt
{% set tests_to_skip = tests_to_skip + ' or test_functional' %}
{% set tests_to_skip = tests_to_skip + ' or test_compare' %}
{% set tests_to_skip = tests_to_skip + ' or test_compare_batched' %}
{% set tests_to_skip = tests_to_skip + ' or test_truncated_compare' %}
# Syspath not found - C:\\Users\\TA0D34~1
{% set tests_to_skip = tests_to_skip + ' or test_pylintrc' %}  # [win]
{% set tests_to_skip = tests_to_skip + ' or test_pyproject_toml_parentdir' %}  # [win]
{% set tests_to_skip = tests_to_skip + ' or test_one_arg' %}  # [win]
{% set tests_to_skip = tests_to_skip + ' or test_two_similar_args' %}  # [win]
{% set tests_to_skip = tests_to_skip + ' or test_more_args' %}  # [win]
# >   os.remove(tempfile_name)
# E   PermissionError: [Errno 1] Operation not permitted: '/tmp/CONFIG'
{% set tests_to_skip = tests_to_skip + ' or test_writing_to_output_file' %}
test:
  source_files:
    - pyproject.toml
    - tests
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
    - pylint.utils
  requires:
    - git
    - gitpython
    - pip
    - py >=1.11.0,<1.12
    - pytest >=8.4,<9
    - pytest-benchmark >=5.1,<6
    - pytest-timeout >=2.4,<3
    - pytest-xdist >=3.8,<4
    - requests
    - typing-extensions >=4.15,<5
  commands:
    - pip check
    
    - pytest -v tests -k "not ({{ tests_to_skip }})"
    - pylint --help
    - pyreverse --help
    - symilar --help    
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type pylint-config  # [unix]
    - where pylint-config  # [win]

about:
  home: https://github.com/pylint-dev/pylint
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  dev_url: https://github.com/pylint-dev/pylint

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
