{% set name = "pylint" %}
{% set version = "4.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a427fe76e0e5355e9fb9b604fd106c419cafb395886ba7f3cebebb03f30e081d

build:
  number: 0
  skip: true  # [py<3100]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-config = pylint:_run_pylint_config
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - python
    - pip
    - setuptools >=77
  run:
    - python
    - dill >=0.3.7  # [py>=312]
    - dill >=0.3.6  # [py==311]
    - dill >=0.3.7  # [py>=312]
    - platformdirs >=2.2
    - astroid >=4.0.2,<=4.1.dev0
    - isort >=5,!=5.13,<8
    - mccabe >=0.6,<0.8
    - tomli >=1.1  # [py<311]
    - tomlkit >=0.10.1
    - colorama >=0.4.5  # [win]
    - typing-extensions >=3.10.0  # [py<310]
    - typing_extensions >=3.10  # [py<310]
  run_constrained:
    - gitpython >3
    - pyenchant >=3.2,<4.dev0

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports
    - pylint.utils
  requires:
    - git
    - gitpython
    - pip
    - py >=1.11.0,<1.12
    - pytest >=7.4.0,<8
    - pytest-benchmark >=4.0,<5
    - pytest-timeout >=2,<3
    - pytest-xdist >=3.6,<4
    - requests
    - typing-extensions >=4.12,<5
  source_files:
    - pyproject.toml
    - tests
  commands:
    - pip check
    # Hardcoded test output does not work in our test environment due to pylint being seen as a local package. Updating
    # the function output was tested; however, dependant tests continue to fail. Disabling for now.
    # https://github.com/pylint-dev/pylint/blob/v3.2.7/tests/functional/w/wrong_import_order.txt
    - pytest -v tests -k "not (test_functional[wrong_import_order] or test_compare[both_empty] or:
        - test_compare[no_change] or test_compare[message_changed] or test_compare_batched or test_truncated_compare)"
    - pylint --help
    - pyreverse --help
    - symilar --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type pylint-config  # [unix]
    - where pylint-config  # [win]

about:
  home: https://www.pylint.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  dev_url: https://github.com/pylint-dev/pylint

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
