{% set name = "pylint" %}
{% set version = "1.8.3" %}
{% set sha256 = "c77311859e0c2d7932095f30d2b1bfdc4b6fe111f534450ba727a52eae330ef2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-gui = pylint:run_pylint_gui
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  build:
    - python
    - pip
    - pytest-runner

  run:
    - python
    - astroid >=1.5.1
    - backports.functools_lru_cache  # [py27]
    - configparser                   # [py27]
    - singledispatch                 # [py27]
    - colorama                       # [win]
    - six
    - isort >=4.2.5
    - mccabe

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pylint --help
    # Needs to start a GUI with Tk.
    # So running help is not even an option.
    # Just check that it exists.
    - which pylint-gui  # [unix]
    - where pylint-gui  # [win]
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - which epylint     # [unix]
    - where epylint     # [win]
    - pyreverse --help
    - symilar --help

about:
  home: https://github.com/PyCQA/pylint
  license: GPL 2
  license_file: COPYING
  summary: 'python code static checker'

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
