travis:
  secure:
    BINSTAR_TOKEN: nYS5k0gj/B1L3yN+9nzvEsAgj2gb2Bysg6uPicVVi1cYDcMdvZZWumszdKwRxMDCZK60p8OICY1dxGnOMpgCCfnW3L+FHwm5D2vxXcUS6mqiEHb9kA5uRuxgaWgMBhQLXzeYjfJRcf/pcKhA+NSgdapJ/iiAvLMf+mIiRpQKJ1lLEe5224b7eocPkwmwZK1pnpe9+eOFBWOWUVQCA7MAAU1vny6dR3ARAMWvCAXl9fdLuNfiUFHlXchIOzjjBFEWJOf/NBPjdj4LeA3VqA7Fg/TGECjwzaIV9ZR32aACbK8DBvgMqSD6pmHwka4NO9mnH/J8nlTuGWIiSXQgrQ0P33p9qatZIbqrNjcIXaQzx7V0/IaZAFEE/asi1aBM0FGJB6Y3TULuUV7jgT8rLouV3O5KjJS8Ts1R1IK/60YSeF+wnX0/tCkk8TDexx5FR187CkzH5Tz0hgsAgp4ugLoIET2jYQ6ODdud28vUkSoN6xNGhyH1GAmWMLlxIYpnvxO9XENn2av7knzmZuejwtv0vA/pjHTlog02rw5fhrxTKse+db8VRUNpvzZfDbsj0kNJ+xsrD23V0mfkf6umDvVP5McK1VxmW0EvsY5druDC2X/Ju1QIhR5cZxFBmK9wLaBg2JJs3PPFfxwcYMIbHyjd0OeABAx3SviMuNwo4gmhBgE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
