travis:
  secure:
    BINSTAR_TOKEN: mpJIr4puFlI8HhXAK5PxMfGJm8YffHg+PCb7jIwz0/n3l3oN1In7XqKHyRzZr4bVfnyDOAm6Hq30+NbsUaDN1le2TQFfGD4TbhZHwtWThRLIaA1IC9fIMC+PTimChP2SIeUVJHgmoHMCkaOpQd1JBFRKETFgUJ2FoCS8BaTBIBNetSoqLX0om478URHlsIXlEV+BolTWMTax4y8iKEHVkBAbq25BkskYAFkgx1+9m4lk7NKyLHAhenCHLPp5OSnyTCk0r0VpLWO2/nt/1HpKieUpQxo+xwLnYHfzC0e1hfT03B43es8AbKC/5j+eJ0oj3A/vZG+MtI8xq44ETsm058RNKdaphJMufW7CA2Z7/LoGI6kx/KQyI4KUkSOK6q8dOFgr0tS4Ho3+/T7m7y0jFJ/KSjxX19UGp8MFgpnbPNU2va0qIWXXxHezSmT8qMgF6YnU4cs6g8CVIyef5pRjxrkFqeNvn5E53xiJTbBEbUmH+DHo7TvTiHW68VBMpbMmqVS3H9uy2ujBcSxYyvp94pL//WZ7/VLohsx+AwYDxNwOcPF92WA/dFWGxAEJjXqN49ltqYGTuS91Gt0w/dxdTwDWWGKWurI9+3LrrsjqTpWigG53a4NOA1sip4BP5FwrQW5ShaWV+e7oz1KzWmWzy8Z1pBJVkjeIxdQwJAlVazA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
